# Generated by Django 4.1.4 on 2022-12-20 19:10

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите телефонный номер', max_length=15, region=None, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Введите адрес электронной почты', max_length=254)),
                ('name', models.CharField(help_text='Введите ваше имя', max_length=200, verbose_name='Имя')),
                ('message', models.TextField(help_text='Напишите сообщение', verbose_name='Сообщение')),
            ],
        ),
    ]
